### ISSUE TITLE
in the calico launch docs core-01 and core-02 flipped

### ISSUE THREAD

**Issue by liljenstolpe** [Metaswitch/calico-docker#1]
Greetings core-01 and core-02 are flipped in the peer settings in calico launch

**Comment by ed-harrison** [comment]
I believe this was fixed by https://github.com/Metaswitch/calico-docker/commit/88fe28d79ea0716bbfe5c25f3f516138fa440a8d.

**Comment by Lukasa** [comment]
Looks like.
