### ISSUE TITLE
How can i expose a port?

### ISSUE THREAD

**Issue by frostynova** [Metaswitch/calico-docker#100]
If i have a nginx container managed by calico,  how can i expose its port 80 to make it communicate with outside network?
I found ```docker run -p``` didn't work.

**Comment by frostynova** [comment]
Maybe one solution is keeping the docker0 interface ?

**Comment by Symmetric** [comment]
If you connected containers to the docker0 interface, then we would not be able to enforce security rules between workloads; all containers on the bridge would be able to communicate with each other.

To open a port, you should modify the rules in the container's profile.

See the [Advanced Networking Guide](https://github.com/Metaswitch/calico-docker/blob/master/docs/AdvancedNetworkPolicy.md) for details and examples, but you need to add a rule like this:

```
"inbound_rules": [
    {
      "action": "allow", 
      "protocol": "tcp",
      "dst_ports": [80]
    },
    ...
]
```

**Comment by spikecurtis** [comment]
@frostynova or are you asking how to allow IP speakers outside the Calico container network to connect to your containers?

The short answer is that Calico looks like an ordinary routed IP network, with each compute host acting as a router speaking BGP.  You'll need to set up an edge router to connect the Calico network to the external network.  Setting this up requires you to manipulate the etcd data directly, since we don't have a `calicoctl` command for it.

If that's what you're looking to do we can prioritize writing a doc for this.

**Comment by frostynova** [comment]
@spikecurtis yes that is what i want. We have nginx containers which accept external requests. Looking forward to have a doc for this. Thanks.

**Comment by spikecurtis** [comment]
I just wanted to say that we're all at a conference this week, so it'll be next week before I have a chance to write this.

http://docs.projectcalico.org/en/latest/addressing.html

is a good overview of how this works (focusing on VMs, but you can just think of containers when they talk about VMs).  I'll cover specifically how to do this with calico-docker.

**Comment by lxpollitt** [comment]
@frostynova - If you need more help before @spikecurtis is available, then please let us know.

**Comment by frostynova** [comment]
@lxpollitt @spikecurtis 
I read the doc @spikecurtis mentioned, and this: https://github.com/Metaswitch/calico-docker/issues/87#issuecomment-94596735

Seems it only need to add another ip to the container interface and modify the relative etcd key?

**Comment by frostynova** [comment]
After manually add a FORWARD rule and a PREROUTING rule, i made a port export to outside.
But this need to exec iptables command on the hosts

**Comment by lxpollitt** [comment]
@frostynova - I think it would be really helpful if we could schedule a call to discuss exactly what you are trying to achieve so we can best advise you on how to do it with the particular physical network topology you have.  There are a few different options and we would like to understand which would fit best for you.  What time zone are you located in?

**Comment by frostynova** [comment]
@lxpollitt since my bad spoken english, i am afraid a call is something difficult. I could try to give an example

Our hosts' subnet is 10.100.0.0/16 and containers' subnet is 192.168.0.0/16 which is managed by calico. One of the containers is running nginx which is our app's web router

Before using calico, i can just expose port 80 of the nginx container to let client in host subnet access the web router. Now after using calico, expose takes no effect, how can i do that?

One method i found is adding some iptables rules on the host running nginx container. But this is ugly, so i wonder if there is an offical method to do that? thanks

**Comment by lxpollitt** [comment]
@frostynova - Are your hosts connected by physical L2 network?  And that L2 network is also connected to your border router?

Or is your physical network L3?

If you can answer the above then we should be able to point you are the best option to achieve what you are trying to do.


As background, in most Calico deployments people choose to peer with their L3 network elements (such as the border router) using BGP.  That way the border router knows how to route packets to your containers  containers via the hosts IP address.  You can then choose whether you want your border router to do incoming NAT or whether you want to give your nginx container an external IP address.  The packets would get from the border router to the nginx container via the same routes in both case.

Another approach is to install NAT rules locally on the host of the nginx container.  From what you said earlier it sounds like that is what you are trying to do.  That can work fine, but Calico doesn't yet include support for automatically programming those NAT rules into the host, so you will need to do this yourself.  We an provide help if you are not sure what those rules should look like.

**Comment by frostynova** [comment]
@lxpollitt Thanks to the detailed answers. Unfortunately, the physical network router is not under our control now, so i think we will work on NAT rules.

**Comment by fasaxc** [comment]
Hi @frostynova, are you running on top of a particular cloud provider, such as GCE or AWS?

**Comment by frostynova** [comment]
@fasaxc Not yet. Currently, we still deploy on physical servers, but in the future, we hope our project can be deployed in the environment as much as possible.

**Comment by tomdee** [comment]
@frostynova Hopefully our docs are now clearer on this issue. If you're still hitting problems or the docs are unclear then please do open another issue.

**Comment by fzhouse** [comment]
@frostynova Have you solved the problem with calico? I met the same problem with calico 0.12.0-dev. After I start the calico-node, I run 'docker run -tid -p 80:80 nginx' on physical host 10.0.0.1, I am able to access the nginx through http://10.0.0.1:80. However, after I add a new port to the docker with calico, I cannot access the nginx any more. Is there any way to solve this without adding iptable rules on the physical host now?

**Comment by frostynova** [comment]
@fzhouse Do you use Calico with Docker Libnetwork? How do you "add a new port to the docker"? Now our solution is still use iptables with DNAT rules.

**Comment by fzhouse** [comment]
@frostynova I am sorry for my poor expression. What I mean is that I start a docker with 'docker run --name webserver -tid -p 80:80 nginx' and I am able to access the docker with the host ip address and port 80. However, After I run 'calicoctl container add webserver 192.168.0.1', I am no longer able to access the nginx with the host IP and port 80. For now, I can only export the port of the docker using iptables with DNAT rules on the physical host, which I think is the same as what you have done.

**Comment by frostynova** [comment]
@fzhouse One possible answer is calico changed the container's default route, so your packet can reach the container, but cannot route back.  You can view the default route in the container or run tcpdump to see if the container has received the packets..

**Comment by spikecurtis** [comment]
@fzhouse are you using the Calico driver with Docker 1.9 (e.g. `docker network create` commands)?
