### ISSUE TITLE
Add ability to network an existing container

### ISSUE THREAD

**Issue by plwhite** [Metaswitch/calico-docker#12]
The main use case is where you create a container using the standard docker bridge, then want to add a Calico interface complete with IP and route (so that you have a container with a both a docker bridge for management and a Calico routed IP). At the point where the Calico interface is added, the default route on the container would change to use the Calico IP rather than the bridge.

To be clear, this doesn't cover having multiple Calico interfaces, each with its own IP (though that's a possible future enhancement), just having a Calico interface and a non-Calico one.

**Comment by tomdee** [comment]
So, the route to the dockerbridge IP range should stay intact?

**Comment by plwhite** [comment]
Yes, I think so.

**Comment by spikecurtis** [comment]
Fixed in v0.0.7.
