### ISSUE TITLE
Calico-docker releases are no longer tied to specific felix releases.

### ISSUE THREAD

**Issue by tomdee** [Metaswitch/calico-docker#123]
Since the 0.4.1 release. 

We will fix this in a 0.4.2 release shortly.

**Comment by alexaltair** [comment]
Since the 0.4.1 release.*

**Comment by tomdee** [comment]
That's what I said :-)

**Comment by tomdee** [comment]
The felix debs are now published on launchpad which doesn't easily allow multiple versions to be uploaded. So closing as wontfix.
