### ISSUE TITLE
FVs take a long time

### ISSUE THREAD

**Issue by alexaltair** [Metaswitch/calico-docker#127]
Running the bare scripts took 2 minutes. Some as-yet-diagnosed change has caused them to take 10 minutes. Running them with multiple hosts, (docker-in-docker) takes 25 minutes.

**Comment by tomdee** [comment]
@alexaltair Have you got to the bottom of this yet? If you have, can you close it.

**Comment by alexaltair** [comment]
We made a lot of progress, but I want to keep evaluating it while I rewrite them in python.
