### ISSUE TITLE
Calico doesn't pass docker the container's IPv6 address?

### ISSUE THREAD

**Issue by alexaltair** [Metaswitch/calico-docker#176]
To repro, pause at the end of the ST `test_ipv6` or run the equivalent commands manually. After you've created workloads with IPv6 addresses, do a `docker inspect node1`. You'll see that the field `NetworkSettings.GlobalIPv6Address` is empty. If you run `docker exec node1 ip -6 addr` you'll see that the container does have an IPv6 address.

**Comment by tomdee** [comment]
This is a powerstrip limitation.

**Comment by spikecurtis** [comment]
I propose we don't fix since we're hoping to deprecate Powerstrip in favor of libnetwork.

**Comment by alexaltair** [comment]
Sounds good to me. There's just a slightly hacky part of the tests that I'll fix after powerstrip is removed.
