### ISSUE TITLE
Argument parsing confuses commands if User-named parameters share words from other commands

### ISSUE THREAD

**Issue by djosborne** [Metaswitch/calico-docker#187]
When running a command that requires a user-generated name (such as naming new profiles or containers), if the provided name is the same as a word in another command, the command parser will execute the wrong command. Naming a container "profile", or naming a profile "container", will confuse the system.

For example, it is impossible to create a container named "profile", as that executes the profile-add command. This is because the arg parsing simply checks if arguments are present, not which order they are passed in. Since profile commands are handled before container commands, the profile commands will see the word "profile" and assume that it is a profile command.

Though it is not recommended that users implement such a confusing naming scheme, the system should be robust enough to understand what is going on.

**Comment by djosborne** [comment]
This scope of this issue has decreased significantly thanks to the new command-submodules from  #291, though I am not convinced that there are still a few edge cases. We will need to investigate further.

**Comment by tomdee** [comment]
I can't see any specific case where this is a problem. Without a repro, I'm going to close this bug tomorrow.
