### ISSUE TITLE
calicoctl node should warn if hostname already exists

### ISSUE THREAD

**Issue by spikecurtis** [Metaswitch/calico-docker#234]
A common problem new users have is trying to set up Calico on a few nodes that don't have unique hostnames.  This is particularly common if they use Vagrant, since they'll often just leave the default hostname.

I propose that `calicoctl node` do a little proactive checking to warn the user if they're likely to run up against this issue:

If the hostname already exists in the etcd database and it has a different IP address than the one the user is configuring, drop a warning:  "Hostname %s is already in use with IP address %s.  Calico requires each compute host to have a unique hostname.  You may ignore this warning if you are reconfiguring the host with name %s"

We should disable this check if `calico-node` is already running on the host, since it's likely that the user is just trying to reconfigure the host.

**Comment by djosborne** [comment]
I'd add that heavy lifting should be done by the `checksystem` command
