### ISSUE TITLE
calico could not assign ip for container

### ISSUE THREAD

**Issue by chanehua** [Metaswitch/calico-docker#269]
hi:
  I base GettingStarted.md this file to config my calico-docker, but calio could not assign ip 
for container,do you have solution?
environment:
sys:ubuntu:14.04
calico version:v0.4.8
etcd:v2.1.0
docker version:1.70 & 1.6.2
thanks

![image](https://cloud.githubusercontent.com/assets/12761229/8482480/7d700322-211c-11e5-8ab8-688123e1a972.png)

**Comment by tomdee** [comment]
The `ip` command isn't very good in busybox. Could you retry either using ifconfig or with a different OS, e.g.
docker run -e CALICO_IP=192.168.100.2 -ti ubuntu

**Comment by chanehua** [comment]
hi:
   “docker run -e CALICO_IP=192.168.100.2 -ti ubuntu” method I have a try,but the result is the same as busybox.
“using ifconfig” I don't know how to config,I would like to ask how to view the calico config's log and the etcd Whether has a special configuration?
thanks!

**Comment by tomdee** [comment]
When you say the result is the same on Ubuntu, do you mean you're seeing a Segmentation fault?

**Comment by chanehua** [comment]
I just look at the container's IP with my config's ip is not the same.

**Comment by spikecurtis** [comment]
I think the issue is that you exported `DOCKER_HOST` for the `cspark` user, but then run `docker run` as root.  See https://github.com/Metaswitch/calico-docker/blob/master/docs/Troubleshooting.md#sudo-docker-run-and-environment-variables

**Comment by chanehua** [comment]
You are right, After I add  my user to docker group,execut the "export DOCKER_HOST" and run a contariner with my usre,the container assign the ip.very thanks!
