### ISSUE TITLE
getting started instructions look out of date

### ISSUE THREAD

**Issue by DaveLangridge** [Metaswitch/calico-docker#277]
I attempted to attach to a container using 'DOCKER_HOST=localhost:2375 docker attach workload-A' but I got:
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
@fasaxc had a look:
Newest version o fdocker seems to listen on a unix socket instead
Try: unix:///var/run/docker.sock

 DOCKER_HOST=unix:///var/run/docker.sock docker attach workload-A 
worked fine

**Comment by tomdee** [comment]
DOCKER_HOST=unix:///var/run/docker.sock is typically the default so there should be no need to set that environment variable. It's left over from the powerstrip integration.

**Comment by tomdee** [comment]
@TrimBiggs Can you fix up the docs?

**Comment by TrimBiggs** [comment]
Will do.

**Comment by TrimBiggs** [comment]
Getting Started was updated with the release of v0.5.0 yesterday
