### ISSUE TITLE
Creation of global config in etcd shouldn't be gated on whether the config directory exists

### ISSUE THREAD

**Issue by tomdee** [Metaswitch/calico-docker#290]
e.g. see https://github.com/Metaswitch/calico-docker/blob/powerstrip-archive/calico_containers/adapter/datastore.py#L423

It should check for each piece of config and create it, rather than just look to see if the directory exists.

**Comment by TrimBiggs** [comment]
@tomdee, the branch you're referencing in that comment is the powerstrip-archive branch.

The master branch is here and has the check reading for a the InterfacePrefix key specifically:
https://github.com/Metaswitch/calico-docker/blob/master/calico_containers/pycalico/datastore.py

I think this is sufficient for being explicit about checking for the key.  What do you think?

**Comment by tomdee** [comment]
Yep. You can close the issue.
