### ISSUE TITLE
calicoctl rule 'to' clause doesn't work following a 'from tag'.

### ISSUE THREAD

**Issue by matthewdupre** [Metaswitch/calico-docker#316]
For example:

`calicoctl profile PROFILE1 rule add inbound allow udp from 192.168.0.1 to 192.168.0.2` works, but
`calicoctl profile PROFILE1 rule add inbound allow udp from tag PROFILE1 to 192.168.0.2` doesn't.

There isn't really any workaround for this, because the 'from' has to precede the 'to' (and someone might want to pass two tags anyway.

**Comment by matthewdupre** [comment]
(By works, I mean the command is accepted (no output), and by doesn't I mean rejected by printing the usage statement.)

**Comment by matthewdupre** [comment]
I've tried this using the `rule update < json` command with the above "doesn't work" rule, and that works fine.  The `rule show` command also works.

**Comment by TrimBiggs** [comment]
Here's the command that the below input should be matching:
`calicoctl profile PROFILE1 rule add inbound allow udp from tag PROFILE1 to 192.168.0.2`

```
calicoctl profile <PROFILE> rule add (inbound|outbound) [--at=<POSITION>]
    (allow|deny) [(
      (tcp|udp) [(from [(ports <SRCPORTS>)] [(tag <SRCTAG>)] [<SRCCIDR>])]
                [(to   [(ports <DSTPORTS>)] [(tag <DSTTAG>)] [<DSTCIDR>])] |
      icmp [(type <ICMPTYPE> [(code <ICMPCODE>)])]
           [(from [(tag <SRCTAG>)] [<SRCCIDR>])]
           [(to   [(tag <DSTTAG>)] [<DSTCIDR>])] |
      [(from [(tag <SRCTAG>)] [<SRCCIDR>])]
      [(to   [(tag <DSTTAG>)] [<DSTCIDR>])]
    )]
```

I think docopt is interpretting the "to" in the 2nd command as the <SRCCIDR>, then sees the 192.168.0.2 and cannot match it to any of its possible input criteria.
