### ISSUE TITLE
Calicoctl should have a 'version' command

### ISSUE THREAD

**Issue by TrimBiggs** [Metaswitch/calico-docker#319]
There should be a simple way to check the version of calicoctl being used.

Having a command like `calicoctl version` that prints the version number would be simple and useful.

**Comment by TrimBiggs** [comment]
It would probably also be useful for this to print the commit id since people might be pulling the actual code and building directly.

**Comment by loshkovskyi** [comment]
+1

and it could be easily extended in the future with other useful information, for example, with client API version (just like in `docker version`).

**Comment by lxpollitt** [comment]
And probably useful to report Felix version too if that it feasible?

**Comment by alexwlchan** [comment]
Closed by PR #414?

**Comment by robbrockbank** [comment]
Fixed by #414
