### ISSUE TITLE
Allow range of IPs to be specified with a pool

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico-docker#340]
Mentioned by @makuk66, who connected over IRC.  He'd a like a bit more control over which IP addresses are used in a pool.  Rather than the whole subnet, it'd be great to be able to use a range within a subnet:
```
192.168.0.100 - 192.168.0.150
```

**Comment by tomdee** [comment]
Should be straightforward. 

We're also planning to add more commands around assigned IPs (which is one of the uses for the pools).
