### ISSUE TITLE
Running calicoctl node without --ip detects the IP address docker0 bridge

### ISSUE THREAD

**Issue by tomdee** [Metaswitch/calico-docker#343]
Calicoctl node has an optional --ip argument to control which IP should be used by bird for BGP peerings (among other things).

When --ip isn't used, calico detects what IP address to use, but it often detects the IP address of the docker0 bridge. I can't see a situation where this is useful, so that interface should be skipped.

**Comment by spikecurtis** [comment]
c.f. https://gist.github.com/makuk66/a5b0c61648b17965fe49
