### ISSUE TITLE
Warn if ipip module not loaded

### ISSUE THREAD

**Issue by amouat** [Metaswitch/calico-docker#346]
I spent the morning trying to network two boot2docker VMs provisioned by docker-machine running the experimental branch of docker. Everything seemed to install ok, but my containers couldn't talk to each other or be pinged on their calico addresses, even within the same host.

After some investigation, it seems to be because boot2docker does not include the ipip kernel module. It took me all morning to figure this out - I wonder if a check could be added to calico to warn if the module is not present? Perhaps on running `calicoctl checksystem`?

Perhaps this issue should be moved to the main calico project, but I was following the instructions for the plug-in, and I'm not sure what belongs to what...

**Comment by spikecurtis** [comment]
@amouat Working on reproducing this.  Did you enable `--ipip` for any of your IP address pools?  Or does Calico fail to work even if you weren't using `--ipip`?

**Comment by amouat** [comment]
Nothing was working, so I looked through the logs and found errors in `/var/log/calico/felix/current` related to ipip. I just assumed this was the cause. I hadn't enabled `--ipip`.

**Comment by tomdee** [comment]
#368
