### ISSUE TITLE
Vagrant guide lists incorrect hostnames

### ISSUE THREAD

**Issue by djosborne** [Metaswitch/calico-docker#377]
Hostnames listed in the "GettingStartedGuide.md" guide are set to `ubuntu-1` and `ubuntu-2`, whereas hostnames listed in the ubuntu-vagrant-guide are set to `calico-1` and `calico-2`.

The getting started guide claims to use the same hostnames from the ubuntu-vagrant-guide, so we should change one or the other to match correctly.

**Comment by tomdee** [comment]
I'm in the process of fixing this up.

**Comment by robbrockbank** [comment]
Fixed by #402
