### ISSUE TITLE
can not using calicoctl in root user

### ISSUE THREAD

**Issue by ninjadq** [Metaswitch/calico-docker#384]
The version I use is 0.4.8. and host OS is centos6.5.
 
When I using normal user and run the following command
```
 $ sudo ETCD_AUTHORITY=127.0.0.1:4001 ./calicoctl node --ip=172.17.33.11 --node-image=calico/node:v0.4.8
```
everything works fine to me.

But now I need to run calicoctl in root user, I run command like  this
```
# export  ETCD_AUTHORITY=127.0.0.1:4001
# ./calicoctl node --ip=172.17.33.11 --node-image=calico/node:v0.4.8
```
the result is 
```
Unable to run docker commands. Is the docker daemon running?
```
It is confused me because docker is running as usual. I can run `docker` command on root user.

Anyone encounter the same problem?  Or it is a bug on calicoctl?

**Comment by tomdee** [comment]
I see you're writing some Python code to integrate with Calico. I'd love to hear more about it?

I'm not sure why calicoctl can't connect to docker. The error is from
https://github.com/Metaswitch/calico-docker/blob/powerstrip-archive/calico_containers/calicoctl.py#L1928
...which indicates a connection error. 

The Docker connection defauls to using the domain socket - see here
https://github.com/Metaswitch/calico-docker/blob/powerstrip-archive/calico_containers/calicoctl.py#L141

Maybe your daemon isn't listening on the domain socket? In which case, can you try setting the DOCKER_HOST environment variable? e.g.
`export DOCKER_HOST=tcp://127.0.0.1:2375`

It's not very clear in our docs, but the version of calicoctl that you run needs to match the calico/node image that you run. Are you sure they are the same? If they are, you shouldn't need the --node-image option.

**Comment by ninjadq** [comment]
Thank you for your reply.
We are developing a system [Eru](https://github.com/HunanTV) that managing containerized applications across multiple hosts just like kubenetes. And wish to integrate calico to Eru as the network module in the near future.
So I wanna write a demo that control calico network on host using restful api.

`DOCKER_HOST` is already set. I think if I don't set it, the `docker` command will also not works but it works well.  
  
the images and calicoctl is the same version, thanks for your advice.

**Comment by ninjadq** [comment]
I'm sorry the problem seems that the `DOCKER_HOST` env var. When I unset this env var, it works now.
Thank you!

**Comment by tomdee** [comment]
No problem, I'm glad to help.
