### ISSUE TITLE
Endpoints for terminated docker containers are not cleaned up

### ISSUE THREAD

**Issue by Symmetric** [Metaswitch/calico-docker#42]
If a docker container terminates (either because its command completed, or because it was stopped/removed), the endpoint that was created in etcd by the powerstrip adapter is not cleaned up.

This leak can cause felix to spew a lot of logs; on my system I'm seeing ~50 logs per second of the form 

```
Mar 19 21:45:11 slave1 calico-felix: Unable to configure non-existent interface tap500dd1d0cd0
```

We could intercept delete events on the docker REST API, but that only covers a subset of container  termination events. To fully fix this leak we'll need Powerstrip to [provide hooks to the docker event stream](https://github.com/ClusterHQ/powerstrip/issues/38).

**Comment by spikecurtis** [comment]
Or, we could just implement our own calico-docker garbage-collection daemon to listen to the Docker event stream.

**Comment by tomdee** [comment]
We expect to fix this as part of integrating with libnetwork. Depending on what happens there, we might still need some garbage collection.

**Comment by tomdee** [comment]
Closing as this is now fixed by the libnetwork integration.
