### ISSUE TITLE
The link to the technical page on the Calico website in the README is broken

### ISSUE THREAD

**Issue by alexwlchan** [Metaswitch/calico-docker#44]
Specifically, this paragraph:

> Calico can provide networking in a Docker environment. Each container gets its own IP, there is no encapsulation and it can support massive scale. For more details see http://www.projectcalico.org/technical/

I get a 404 if I try to visit that page. I assume it got moved around in the website redesign.

I don't know what (if any) is a suitable replacement link. I'd guess http://www.projectcalico.org/learn/, but I'm not totally sure.

(For comparison, the old page is [in Google's cache](http://webcache.googleusercontent.com/search?q=cache:z6sV0Se7IaUJ:www.projectcalico.org/technical/+&cd=1&hl=en&ct=clnk&gl=uk))

**Comment by ed-harrison** [comment]
Good spot - see pull request #45.

**Comment by alexwlchan** [comment]
I've merged pull request #45, so this is fixed.
