### ISSUE TITLE
core-01 and core-02 end up on different VirtualBox Host-only adapters

### ISSUE THREAD

**Issue by ed-harrison** [Metaswitch/calico-docker#5]
When I run "vagrant up" on my system, my two VMs end up on separate Host-only adapaters.  In other words, core-01 will be on adapter #2 while core-02 will be on adapter #3.  In order to proceed through the demo, I need to use the Oracle Virtual Box console to change the settings on one of the VMs (in other words, change core-02 so that it uses adapter #2).

Moreover, if I do a "vagrant destroy" adapters remain in the Virtual Box settings.  The means the next time I run "vagrant up", I get new adapters created (for example core-01 uses adapter #4 and core-02 uses adapter #5).

While this is relatively easily spotted and worked around (and I recognise this might be unique on my installation of Virtual Box ,version 4.3.20 r96997 for Windows), I think the documentation should at least include this as a potential issue in the troubleshooting section.

**Comment by tomdee** [comment]
I'm on the fence about documenting this. It's a vagrant problem, and not one that's unique to calico. No other projects that I've seen that use vagrant document this issue and once we document this problem, it's very hard to ever get rid of it. I think I'd just prefer to close this issue and hope we never see it again. WDYT?

**Comment by lxpollitt** [comment]
Is the problem unique to Ed (i.e. he was just very unlucky) or is there something about Ed's setup that might turn out to be common.  e.g. Particular version of Windows OS, or a particular hardware?

**Comment by tomdee** [comment]
Well, we couldn't work it out at the time and I doubt we'll be able to now. I don't think it's worth us spending (more) time on it and I don't think we need an issue to track it.

**Comment by ed-harrison** [comment]
It could, potentially, be a bad interaction between vagrant/virtualBox and Windows 8 and/or the SP3.  I suspect most/all of our other testers will be using Win 7.  Virtual Box (not Calico!) definitely did something "bad" with my networking as it actually caused my wireless drivers to crash the machine about 15 minutes after going to sleep (a problem which went away as soon as I uninstalled VB).

Personally, I'd be tempted to just enhance the line we already have in the vagrant README.  Let me propose something in a PR and you can decide then.

**Comment by tomdee** [comment]
Merged the vagrant README fix so closing.
