### ISSUE TITLE
Why isn't `CALICO_IP=auto` the default?

### ISSUE THREAD

**Issue by rohansingh** [Metaswitch/calico-docker#52]
When browsing the source, I noticed that using `-e CALICO_IP=auto` will cause calico-docker to auto-assign an IPv4 address. Is there any reason this isn't the default?

When integrating with orchestrators, it's not always reasonable to expect every orchestrator to always pass a `CALICO_IP` environment variable. If an orchestrator is going to the trouble of using the Powerstrip endpoint for Calico (as opposed to just using Docker directly), I'd think the reasonable default would be to auto-assign an available IP from the Calico pool.

**Comment by spikecurtis** [comment]
Right now the Calico adapter for Powerstrip looks for that variable to know which container requests to add Calico to.  The idea is that if that variable isn't present, we wouldn't set up Calico networking (if, for example, you needed to run a container with "host" networking).

As you hinted at, people can always bypass Powerstrip and go directly to the Docker API for that, but that approach won't work if you're using more than one Powerstrip adapter.  For example, you might connect both Flocker and Calico via Powerstrip and want to use Flocker but not Calico for a container.

Anyway, that's the reason it's that way now.  If it's a pain to tweak your orchestrator to pass the environment variable, we could probably add support to configure the Powerstrip adapter to assume CALICO_IP=auto as the default.  Let me know!

One final thing to mention is that Powerstrip is itself a temporary solution for prototyping.  Docker are working on a networking API right now.  We don't know exactly what that will be like, but we're expecting it give us a way to configure extensible Docker networking in a much cleaner way.

**Comment by rohansingh** [comment]
@spikecurtis Thanks for the in-depth explanation! I'm looking into Calico as a possibility for running Kubernetes. For now I'll just always specify the `CALICO_IP` variable for each pod. Thanks again.
