### ISSUE TITLE
confd doesn't handle hostnames (must use IPs for ETCD_AUTHORITY)

### ISSUE THREAD

**Issue by frostynova** [Metaswitch/calico-docker#59]
for example:

[root@d72 ~]# ./calicoctl node --ip=10.100.143.72 --etcd=127.0.0.1:2379
Usage:
  calicoctl node --ip=<IP> [--node-image=<DOCKER_IMAGE_NAME>] [--ip6=<IP6>] [--force-unix-socket]
  calicoctl node stop [--force]
  calicoctl status
  calicoctl shownodes [--detailed]
  calicoctl profile show [--detailed]
  calicoctl profile add <PROFILE>
  calicoctl profile remove <PROFILE>
  calicoctl profile <PROFILE> tag show
  calicoctl profile <PROFILE> tag add <TAG>
  calicoctl profile <PROFILE> tag remove <TAG>
  calicoctl profile <PROFILE> rule show
  calicoctl profile <PROFILE> rule json
  calicoctl profile <PROFILE> rule update
  calicoctl profile <PROFILE> member add <CONTAINER>
  calicoctl ipv4 pool add <CIDR>
  calicoctl ipv4 pool del <CIDR>
  calicoctl ipv4 pool show
  calicoctl ipv6 pool add <CIDR>
  calicoctl ipv6 pool del <CIDR>
  calicoctl ipv6 pool show
  calicoctl container add <CONTAINER> <IP>
  calicoctl container remove <CONTAINER> [--force]
  calicoctl reset
  calicoctl diags

**Comment by spikecurtis** [comment]
It was getting pretty annoying to have to type `--etcd=` for just about every `calicoctl` command. Instead, `calicoctl` reads that information from the environment variable `ETCD_AUTHORITY`

Sorry for the confusion!  I'll make a note to add it to the docs.

**Comment by frostynova** [comment]
@spikecurtis I found another problem, ETCD_AUTHORITY cannot set to "localhost:2379", must be "127.0.0.1:2379", otherwise the calico node cannot start

**Comment by spikecurtis** [comment]
@frostynova Yep, I can repro that behavior on my machine.  Looks like `confd` doesn't handle hostnames.

We should be able resolve that issue in our next release.

**Comment by grkvlt** [comment]
+1 I had the same issues. I also had to discover `ETCD_AUTHORITY` by browsing the code, this should be documented somewhere, probably?

**Comment by tomdee** [comment]
FTR - ETCD_AUTHORITY has been added to the usage string, but the hostname vs. IP issue in confd hasn't been resolved yet.

**Comment by tomdee** [comment]
Could this just be a hosts or DNS issue. We'll need to do some more testing.

**Comment by tomdee** [comment]
@robbrockbank Can you add the details of the testing you did?

This could be an instance of https://github.com/coreos/etcdctl/issues/109 but I think it's unlikely.
It could also be the fact that confd is cross compiled (I think the linux release is build on a mac) which could cause DNS resolver issues - https://inconshreveable.com/04-30-2014/cross-compiling-golang-programs-with-native-libraries/

We could try compiling from source.

**Comment by robbrockbank** [comment]
Testing I did was fairly limited as follows:

- Spin up a calico node (using 127.0.0.1)
- `docker exec -it calico-node bash` to get onto the calico node
- on calico node checked that localhost would resolve (e.g. ping localhost)
- Edit /etc/service/confd/run to replace ${ETC_AUTHORITY} with localhost:4001
- Restart confd service `sv restart confd`
- ps shows confd not running, logs in /var/log/calico/confd.log:

```
2015-05-07T21:36:48Z gulfstream /confd[409]: INFO Backend set to etcd
2015-05-07T21:36:48Z gulfstream /confd[409]: INFO Starting confd
2015-05-07T21:36:48Z gulfstream /confd[409]: INFO Backend nodes set to localhost:4001
2015-05-07T21:36:48Z gulfstream /confd[409]: FATAL cannot connect to etcd cluster: localhost:4001
2015-05-07T21:36:49Z gulfstream /confd[412]: INFO Backend set to etcd
2015-05-07T21:36:49Z gulfstream /confd[412]: INFO Starting confd
2015-05-07T21:36:49Z gulfstream /confd[412]: INFO Backend nodes set to localhost:4001
2015-05-07T21:36:49Z gulfstream /confd[412]: FATAL cannot connect to etcd cluster: localhost:4001
2015-05-07T21:36:50Z gulfstream /confd[415]: INFO Backend set to etcd
2015-05-07T21:36:50Z gulfstream /confd[415]: INFO Starting confd
2015-05-07T21:36:50Z gulfstream /confd[415]: INFO Backend nodes set to localhost:4001
2015-05-07T21:36:50Z gulfstream /confd[415]: FATAL cannot connect to etcd cluster: localhost:4001
2015-05-07T21:36:51Z gulfstream /confd[418]: INFO Backend set to etcd
```
Change run config back to using IP address, all works fine again.

**Comment by loshkovskyi** [comment]
Just came across this issue as well. Can you please add a note about `ETCD_AUTHORITY` to your docs at http://docs.projectcalico.org/en/latest/index.html ? Thanks.

**Comment by tomdee** [comment]
I'm tracking the confd bug here https://github.com/kelseyhightower/confd/issues/309
