### ISSUE TITLE
new docker instance route discovery slow

### ISSUE THREAD

**Issue by frostynova** [Metaswitch/calico-docker#61]
I have built a test environment on Xen Server VMs (on the same physical server), for example host: d72 d73

then i launch some docker containers on them, i found the new container's route rule took up to 2-3 mins to appear in d72 or d73's route table, it is that normal?

**Comment by Lukasa** [comment]
@frostynova Does it just take a long time to appear in the *other* host's routing table? That is, if you create a container on d72, does the container route take a long time to appear in both routing tables, or just d73's?

**Comment by frostynova** [comment]
@Lukasa in both, but i can not reproduce it now. I changed the bird.conf in node container:

protocol kernel {
   -scan time 20;
   +scan time 1;
}

protocol device {
  - scan time 10;
  + scan time 1;
}

now the new route almost appear immediately

**Comment by frostynova** [comment]
@Lukasa  i doubt if reduce the scan interval will cost much more than default configuration?

**Comment by Lukasa** [comment]
The kernel scan time is the important factor: you can leave the device scan time relatively large.

I don't know where your scan times came from, because all the default configurations I can see have the kernel scan time set to 2, which should be low enough for most simple cases.

**Comment by frostynova** [comment]
@Lukasa thanks, i used v0.3.1 default container from there: https://github.com/Metaswitch/calico-docker/releases/

**Comment by Lukasa** [comment]
Hmm, @spikecurtis, any idea how the BIRD container ended up with a large scan time in v0.3.1?

**Comment by fasaxc** [comment]
Marked as a bug, it should be much faster than that.

**Comment by spikecurtis** [comment]
When we start up bird in the calico-node container, bird uses the config at `/config/bird.conf` which should have a scan time of 2 seconds.  Note that it *does not* use the default file location of `/etc/bird/bird.conf`, which might be where you are seeing the longer scan times.

I'll keep digging on why things are taking so long, but I think the kernel scan time is a red herring.

**Comment by Lukasa** [comment]
@spikecurtis Including the change of scan time fixing the problem?

**Comment by spikecurtis** [comment]
Ok, I've repro'd it locally, and I think it's a Felix problem reading from etcd: https://github.com/Metaswitch/calico/issues/323

Felix doesn't get the update from etcd in a timely fashion.  When its connection times out, it re-reads what it missed and gets the updates, but this can be 10s of seconds after the endpoint was created.

**Comment by fasaxc** [comment]
I don't think it's Metaswitch/calico#323; that issue was that the read takes longer to time out than it should due to retries.  I think we've got a more fundamental issue: we have an open watch connection but we don't get the event until after we timeout and retry.

I'm going to capture some tcpdump snoop from my local repro and see if I can pin the blame on one of the components.

**Comment by spikecurtis** [comment]
I think we've isolated this to etcd.  Fortunately, there is a new version that seems to address the issue for me.  @frostynova can you upgrade etcd to 2.0.9 (https://github.com/coreos/etcd/releases/tag/v2.0.9) and let me know if that fixes the issue for you as well?

**Comment by spikecurtis** [comment]
Tracking upstream at https://github.com/Metaswitch/calico/issues/359

**Comment by spikecurtis** [comment]
I've uploaded a new release which works around the underlying issue in python-etc/urllib until we can upstream a fix there.  etcd wasn't the problem.  See https://github.com/Metaswitch/calico/issues/359 for full details.

https://github.com/Metaswitch/calico-docker/releases/tag/v0.3.2

@frostynova You can ignore my previous comment about etcd version upgrade---the new release linked above should work regardless of the etcd version.

**Comment by frostynova** [comment]
@spikecurtis thanks, i will try the new calico-docker version  :)

**Comment by frostynova** [comment]
The new version seems to work well, thanks all
