### ISSUE TITLE
New versions of python-etcd alter exception hierarchy

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico-docker#63]
For my local testing, I've got a newer version of python-etcd (installed from master on Github with some local changes).  The new version has a richer exception hierarchy and doesn't use KeyError for "key not found" and the like.

Not sure when that version will land in PyPI but it breaks calicoctl, which is expecting KeyError.

**Comment by robbrockbank** [comment]
v0.4.0 calico-docker / calicoctl released.

This updates to the latest Felix and uses the new etcd deb for installing etcd.
