### ISSUE TITLE
Add container ID to calicoctl profile show --detailed

### ISSUE THREAD

**Issue by lxpollitt** [Metaswitch/calico-docker#70]
Currently profile show displays two columns: the profile name and the Calico end point ID.  It would be very useful to have a third column that displays the Docker container ID (in the same 12 char abbreviated style that docker ps does).

**Comment by robbrockbank** [comment]
I've added pull request #112 - currently unreviewed.

This adds host, workload type and workload ID to the table.  We could also add IP info in as per the show nodes command...

**Comment by robbrockbank** [comment]
Code now reviewed and merged.
