### ISSUE TITLE
how to change a container's profile?

### ISSUE THREAD

**Issue by frostynova** [Metaswitch/calico-docker#72]
i use:
```
calicocl profile test2 member add xyz 
```
to change container xyz to profile test2, but seems the ipset or iptables rules not changed? xyz still cannot ping other containers in test2

so how can i change a container's profile?

and  if a container wants to communicate with two or more profile, how can i do that?

**Comment by spikecurtis** [comment]
@frostynova you've got the command correct to set the profile (I assume `calicocl` is just a typo and use did use `calicoctl`).  Can you try running `calicoctl diags` and post the link to the diags bundle.  It would also help to know the other commands you ran.

I'm working on an example doc for customizing the network policy, which will include how to allow communication between profiles.  I'll post it shortly.

**Comment by spikecurtis** [comment]
This doc gives some more advanced examples of how to enable communication between different profiles.  Let me know if you have any questions!

https://github.com/Metaswitch/calico-docker/blob/master/docs/AdvancedNetworkPolicy.md

**Comment by frostynova** [comment]
@spikecurtis thanks for the new doc. 

i just reproduce the problem with a clear example (btw, diags cannot run on CentOS 7, no netstat and route command) :

we have two hosts: d72 and d73
on d72 we create two containers and add them to their profiles

1. docker run -e CALICO_IP=192.168.20.2 -td ubuntu --name web_node1
1. calicoctl profile add web
1. calicoctl profile web member add web_node1
1. docker run -e CALICO_IP=192.168.20.3 -td ubuntu --name mysql_node1
1. calicoctl profile add mysql
1. calicoctl profile mysql member add mysql_node1

on d73 we create another container:

1. docker run -e CALICO_IP=192.168.21.2 -td ubuntu --name mysql_node2
1. calicoctl profile mysql member add mysql_node2

now, i can ping from mysql_node1 to mysql_node2
then , add a new profile and put mysql_node1 to this one:

1. calicoctl profile add mysql_portal
1. calicoctl profile mysql_portal member add mysql_nod1

but now, i still can ping from mysql_node1 to mysql_node2, it that a bug or i made wrong steps?

**Comment by frostynova** [comment]
Go on testing, when following the new doc to set profile tags, i made a mistake, i added a tag which name is the same as other profile name. Then everything went wrong, i have to reset all config and iptables' rules to get everything ok.

So if a tag name can not be the same as a profile name, and it is dangerous, i think we need some method to prevent this happen.

**Comment by Lukasa** [comment]
> I found if i start a new ping(or just stop the old one and ping again), the behavior is normal, the new ping cannot ping to mysql_node2. So the profile change will not affect current session?

This is correct. Right now, Calico uses connection tracking to prevent us from needing to insert bi-directional rules that allow established traffic. We *may* want to add functionality to force connection tracking state to be dropped on profile change.

**Comment by spikecurtis** [comment]
Profiles get set up by default with a tag name the same as the profile name---this is just so they behave like a group by default.  Hopefully that explains the behavior you were seeing.  If not, then could you give more detail?

You can remove any tags from the profile you don't want, including the default.

calicoctl profile <profile> tag remove <tag>

**Comment by frostynova** [comment]
@spikecurtis oh, maybe what I said is confused. 

for example, I had two profile A and B, what will happen if I add tag A to profile B? 
I think containers in B can connect to A, but actually they even cannot connet to their hosts ip.

**Comment by spikecurtis** [comment]
Yes, if you add tag A to profile B, then containers in B should be able to connect to A, assuming you left the rules as they were by default.

If that fails then maybe something else is wrong.  Is it reproducable?  Can you send us diagnostics?

**Comment by tomdee** [comment]
Closing. @frostynova please reopen if there's still an issue here.
