### ISSUE TITLE
bird6.conf fails to recognize a host when its name is a prefix of another.

### ISSUE THREAD

**Issue by spikecurtis** [Metaswitch/calico-docker#77]
Created a host `core-01` using `calicoctl`.

Then created a host using `etcdctl` to represent a real router, using the hostname `core-01-tor`.  bird6.conf failed to set up peering to the router.

Tried again with hostname that didn't have `core-01` as a prefix, and it worked.

**Comment by robbrockbank** [comment]
Tried to repro this just using two hosts in the vagrant set up named core-01 and core-01-02.  That worked just fine.

@spikecurtis Could you fill in a little more detail about how to repro this one?

**Comment by spikecurtis** [comment]
@liljenstolpe hit this in the field.  Maybe he can recall other salient details...

**Comment by robbrockbank** [comment]
Talked to Chris.

He added to the etcd config a calico/<host>/bird_ip entry where the <host> prefix was the same as one of the other nodes.

**Comment by tomdee** [comment]
@robbrockbank so, was this user error or a bug? What's the next action on this?

**Comment by spikecurtis** [comment]
Given that @robbrockbank couldn't repro, and we don't have field diags, I'm closing this issue.

It was very easy to get the etcd keyspace into a bad state at the time, given the reliance on `calicoctl reset`.  My best guess is that we misunderstood the cause.  We can reopen if we see it again.
