### ISSUE TITLE
calicoctl addtogroup doesn't support truncated container IDs

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico-docker#8]
I lost my container ID $A/$B/$C variables by quitting SSH and tried running calicoctl addtogroup with the container id from docker ps but it failed:

    $ sudo ./calicoctl addtogroup f58a67cc1cae GROUP_A_C_E
    'Container with ID f58a67cc1cae was not found.'

**Comment by tomdee** [comment]
This is fixed already, it just hasn't made it into a release.
