### ISSUE TITLE
Broken 'Calico CoreOS Vagrant' link

### ISSUE THREAD

**Issue by neiljerram** [Metaswitch/calico-docker#85]
On https://github.com/Metaswitch/calico-docker/blob/master/docs/GettingStarted.md, the link in "Use Calico CoreOS Vagrant to start a cluster in VMs on your laptop or workstation" seems to be broken.  It tries to go to https://github.com/Metaswitch/calico-docker/blob/master/docs/calico-coreos-vagrant, but I get 404 for that.

**Comment by alexwlchan** [comment]
Looks like a typo in the Markdown syntax; should be fixed now.
