### ISSUE TITLE
If env_list is 'null', env_to_dictionary() in powerstrip-calico.py will throw exception

### ISSUE THREAD

**Issue by frostynova** [Metaswitch/calico-docker#92]
We use calico behind swarm-manager which will pass a null Env, this will cause env_to_dictionary() throw:

```
TypeError: 'NoneType' object is not iterable
```

I think it will be better to check the value of env_list first

**Comment by Lukasa** [comment]
Thanks @frostynova: you might want to try the branch in #93 to see if that helps with your problem.

**Comment by frostynova** [comment]
@Lukasa that is LGTM, thx!
