### ISSUE TITLE
Cannot allocate ip when behind swarm

### ISSUE THREAD

**Issue by frostynova** [Metaswitch/calico-docker#94]
After i put the calico behind swarm, it failed to allocate ip for the new created container, the error of powerstrip is:

```
Command 'ip netns exec 8678 ip link set dev tmp70c5b9c4ecd name eth0' returned non-zero exit status 2
```

Then i attached to the container and run this command manually, it said File exists. 
And there was a new interface named  tmp70c5b9c4ecd

Strangely, if the container created by docker run, everything is ok.

So i compared the HTTP packets  between using swarm and using docker run, one of the major difference is swarm use Docker API 1.15 and Powerstrip use Docker API 1.17

Any suggestion? Thx

**Comment by spikecurtis** [comment]
@frostynova, calico-docker doesn't support Docker Swarm yet, but we're interested in getting it working.

Can you give more detail on how you set up your Swarm?  Are you running a `calico-node` container on every host in your swarm?  How have you set up Swarm to talk to the Powerstrip port, rather than the usual Docker port?

**Comment by tomdee** [comment]
@frostynova where do you get the "Powerstrip uses docker API 1.17" information from? As far as I know, powerstrip just passes requests through.

**Comment by tomdee** [comment]
@frostynova I'm also interested in your architecture here. Are you running `calicoctl node` directly on the hosts, or running launching the calico node container through swarm? 

I've launched my calico nodes outside of swarm (using the normal `calicoctl node` command)
I've got `swarm join` talking to the powerstrip port and I can run containers through swarm and have calico assign IPs to them. I then launched swarm using
````
SWARM=$(docker run --rm swarm create)
docker run -d --name swarm-node swarm join --addr=10.0.2.15:2377 token://$SWARM
docker run -d --name swarm-manage -p 9999:2375 swarm manage  token://$SWARM
````

And I created my container like this. First without calico then another with calico.
````
gulfstream@gulfstream:~/calico-docker$ docker  -H tcp://localhost:9999 run --rm -ti ubuntu ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:0a:01:00:19  
          inet addr:10.1.0.25  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:aff:fe01:19/64 Scope:Link
          UP BROADCAST  MTU:1500  Metric:1
          RX packets:1 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:110 (110.0 B)  TX bytes:90 (90.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

gulfstream@gulfstream:~/calico-docker$ docker  -H tcp://localhost:9999 run  -e CALICO_IP=auto -tid --name=test ubuntu 
14601bde6377b2a931a620392ad79205bdb9ab87fb1df086d0cddc92374a756b
gulfstream@gulfstream:~/calico-docker$ docker exec test ifconfig
eth0      Link encap:Ethernet  HWaddr 02:bd:b1:0c:c5:1e  
          inet addr:192.168.0.2  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: fe80::bd:b1ff:fe0c:c51e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:19 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4293 (4.2 KB)  TX bytes:578 (578.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
````

**Comment by frostynova** [comment]
@spikecurtis @tomdee 

Our architecture is almost the same with your example:

- Calico-node start first (started by calicoctl node)
- Then swarm-agent (not managed by calico)
- But the request is from a private Go app not ```docker run```

I tried your method which use ```docker -H``` to start a container managed by calico, everything is fine.

So i think maybe the problem is our Go app use a wrong JSON Struct, i will continue to debug on this, thank you.

**Comment by frostynova** [comment]
@tomdee After some testing, i found the problem is in API ```start```, the calico powerstrip do not accept non-empty POST DATA in ```start``` request, for example:

config.json
```
{
    "AttachStderr": false,
    "AttachStdin": false,
    "AttachStdout": false,
    "Cmd": [
        "tail",
        "-f",
        "/etc/hosts"
    ],
    "CpuShares": 0,
    "Cpuset": "",
    "Domainname": "",
    "Entrypoint": null,
    "Env": [
        "CALICO_IP=auto"
    ],
    "ExposedPorts": {
        "6000/tcp": {}
    },
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "Dns": null,
        "DnsSearch": null,
        "Links": null,
        "LxcConf": null,
        "NetworkMode": "",
        "PortBindings": null,
        "Privileged": false,
        "PublishAllPorts": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },
        "SecurityOpt": null,
        "VolumesFrom": null
    },
    "Hostname": "",
    "Image": "ubuntu",
    "Labels": null,
    "Memory": 67108864,
    "MemorySwap": 0,
    "NetworkDisabled": false,
    "OnBuild": null,
    "OpenStdin": false,
    "PortSpecs": null,
    "StdinOnce": false,
    "Tty": false,
    "User": "",
    "Volumes": null,
    "WorkingDir": ""
}
```

We use this config to create a container first (through calico port 2377, our vagrant ip is 192.168.77.21):
```
curl -X POST -H "Content-Type: application/json" -d @config.json 'http://192.168.77.21:2377/v1.15/containers/create?name=hello.web.foo.v2-1'

{"Id":"a0badbb308aa3428abfcc6885e257951e7e06c8b4124eab1d1a87ba6782f0e8d","Warnings":null}
```

Then start this container:
```
curl -X POST -H "Content-Type: application/json" 'http://192.168.77.21:2377/v1.15/containers/a0badbb308aa3428abfcc6885e257951e7e06c8b4124eab1d1a87ba6782f0e8d/start'
```

Everything is OK

But if we add a POST DATA(no matter a string or a json) when start the container, powertrip will fail:
```
curl -X POST -H "Content-Type: application/json" -d xxxx 'http://192.168.77.21:2377/v1.15/containers/a0badbb308aa3428abfcc6885e257951e7e06c8b4124eab1d1a87ba6782f0e8d/start'
```

I think this behavior is different from origin docker daemon which will not fail in this situation.

**Comment by frostynova** [comment]
In Docker API v1.15 Doc, we can see it need a POST DATA when starting a container (although it seems    to be useless)

http://docs.docker.com/reference/api/docker_remote_api_v1.15/#start-a-container

**Comment by tomdee** [comment]
@bincarlos Do you know what could be going wrong here? Does powerstrip have special handling of the start request?

**Comment by Symmetric** [comment]
@frostynova , can you create a gist with the contents of your `/var/log/calico/powerstrip-calico.log` file on the node (preferably captured immediately after reproducing the issue)? Or just tail that file and see if it changes when you post to the /start API endpoint?

The /start request should be hitting our adapter's post-hook handler, which would produce logs (and hopefully an exception if it's a bug in our code) but if it's a Powerstrip issue then we wouldn't see any logs at all.

**Comment by tomdee** [comment]
@frostynova I've pushed a branch so that calico hooks in the /start API request use version 1.15 of the remote API instead of 1.16. This might fix your problem.

The branch name is older-docker-api

You'll need to build a new calico-node image - instructions should be in the docs directory but let me know if you have problems.

**Comment by binocarlos** [comment]
@tomdee @frostynova Hi - there isn't anything particular Powerstrip is doing with a start request - it matches the routes in `adapters.yml` and is somewhat blind to their meaning.  The same is true for API versions - adapters.yml has wildcards for the version in the url e.g. `/*/containers/create` and passes the requested url back to Docker unmolested (after the pre-hooks have run)

I just gave this a try with the slowreq adapter to isolate problems with Powerstrip itself and both examples were OK - as @Symmetric says the output of the calico log would be useful.

`docker logs powerstrip` - any nasty stuff with Powerstrip itself usually shows up here.

**Comment by frostynova** [comment]
@Symmetric The log gist: https://gist.github.com/frostynova/7581b5708f4cbaaa500e
@tomdee I will try it, thx

**Comment by frostynova** [comment]
Sorry for later response, i tried the master code and found it has been fixed, thanks all
