### ISSUE TITLE
docker inspect cannot fetch IP information

### ISSUE THREAD

**Issue by frostynova** [Metaswitch/calico-docker#95]
```
export DOCKER_HOST=127.0.0.1:2377
docker run -e CALICO_IP=auto -td ubuntu
```

Docker inspect output:

```
   "NetworkSettings": {
        "Bridge": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "PortMapping": null,
        "Ports": null
    },
```

**Comment by tomdee** [comment]
Likely won't fix until we move away from powerstrip. This should be in time for the Docker 1.7 release Due in June.

**Comment by frostynova** [comment]
@tomdee So is there anyway i can patch powerstrip myself to get the IP Address? Such as Add a hook for the ```Get``` request? Does powerstrip support this?

**Comment by Symmetric** [comment]
@frostynova I wrote some code to handle `docker inspect` calls as part of an experimental branch, you could take a look at that:

https://github.com/Symmetric/calico-docker/commits/kubernetes-powerstrip

The main commit I think you'll need to cherry-pick is https://github.com/Symmetric/calico-docker/commit/e1f9a8cef2a5ea305fa1ed98432a54dc91a3b45d.

We'd happily accept a PR for this, so let us know how you get on.

**Comment by robbrockbank** [comment]
The latest master now has a fix for this, based on the branch that @Symmetric mentioned above.
